name: go-ci

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scripts

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: scripts/go.mod
          cache-dependency-path: scripts/go.sum

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...

      - name: Build
        run: go build ./...
